Repository ucsb-cs156-f22/f22-6pm-courses, pull requests merged in 2022-11, with the labels that each got.

#6 CVS - changed 'Example' to 'UCSB Courses Search'
  frontend/src/main/components/Nav/AppNavbar.js
Labels: 5, f22-6pm-2

#8 VL - BACKEND: PersonalSchedule name and quarter pair must be unique
  src/main/java/edu/ucsb/cs156/courses/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesController.java
  src/main/java/edu/ucsb/cs156/courses/repositories/PersonalScheduleRepository.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesControllerTests.java
Labels: 10, f22-6pm-2

#13 YL - Add String sourceRepo to systeminfo #12
  src/main/java/edu/ucsb/cs156/courses/models/SystemInfo.java
  src/main/java/edu/ucsb/cs156/courses/services/SystemInfoServiceImpl.java
  src/main/resources/application.properties
Labels: 10, f22-6pm-1

#10 ZG - add character length limit for PersonalSchedule name
  frontend/src/main/components/PersonalSchedules/PersonalScheduleForm.js
  frontend/src/tests/components/PersonalSchedules/PersonalScheduleForm.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesCreatePage.test.js
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesController.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesControllerTests.java
Labels: f22-6pm-2

#16 YL - Modify footer to take value of source repo from /api/systemInfo instead of being hardcoded
  frontend/src/fixtures/systemInfoFixtures.js
  frontend/src/main/components/Nav/Footer.js
  frontend/src/main/utils/systemInfo.js
  frontend/src/stories/components/Nav/Footer.stories.js
  frontend/src/tests/components/Nav/Footer.test.js
  frontend/src/tests/utils/systemInfo.test.js
  src/test/java/edu/ucsb/cs156/courses/controllers/SystemInfoControllerTests.java
Labels: f22-6pm-1

#23 Saahil swap
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/CourseSearches/CourseSearchesIndexPage.js
  frontend/src/stories/pages/HomePage/CourseSearches/CourseSearchesIndexPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/CourseSearch/CourseSearchIndexPage.test.js
Labels: 5, f22-6pm-1

#26 VL - Adjust PSCourse post method to add both primary and secondary
  src/main/java/edu/ucsb/cs156/courses/controllers/PSCourseController.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PSCourseControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/documents/SectionFixtures.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBCurriculumServiceTests.java
Labels: 20, f22-6pm-2

#28 VL - Bug Fix: adjust PSCourse post method to add both primary and secondary
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
Labels: 5, f22-6pm-2

#30 Trista frontend unique pair
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesCreatePage.js
  frontend/src/tests/pages/CourseSearch/CourseSearchIndexPage.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesCreatePage.test.js
Labels: f22-6pm-2

#31 ZG - add PersonalSectionsTable component
  frontend/src/fixtures/personalSectionsFixtures.js
  frontend/src/main/components/PersonalSections/PersonalSectionsTable.js
  frontend/src/stories/components/PersonalSections/PersonalScheduleTable.stories.js
  frontend/src/tests/components/PersonalSections/PersonalSectionsTable.test.js
Labels: 10, f22-6pm-2, STAFF-merge-when-ci/cd-green

#33 YL - Add Quarter.java and QuarterTests.java to models
  src/main/java/edu/ucsb/cs156/courses/models/Quarter.java
  src/test/java/edu/ucsb/cs156/courses/models/QuarterTests.java
Labels: 10, f22-6pm-1

#27 BOB/MX - Created dropdown for PersonalSchedule
  frontend/src/fixtures/personalSchedulesFixtures.js
  frontend/src/main/components/PersonalSchedules/SinglePersonalScheduleDropdown.js
  frontend/src/stories/components/PersonalSchedules/SinglePersonalScheduleDropdown.stories.js
  frontend/src/tests/components/PersonalSchedules/SinglePersonalScheduleDropdown.test.js
  frontend/src/tests/pages/CourseSearch/CourseSearchIndexPage.test.js
Labels: f22-6pm-2, FIXME: Changes Requested

#45 YL - Course Over Time Part One Add Query
  src/main/java/edu/ucsb/cs156/courses/collections/CourseOverTimeCollection.java
Labels: 5, f22-6pm-1

#47 Saahil Section/Course search swap
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/HomePage.js
  frontend/src/main/pages/SectionSearches/SectionSearchesIndexPage.js
  frontend/src/stories/pages/HomePage/SectionSearches/SectionSearchesIndexPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/HomePage.test.js
  frontend/src/tests/pages/SectionSearches/SectionSearchesIndexPage.test.js
Labels: 10, f22-6pm-1

#55 Fixed BUG: Update Courses DataBase, First Use fails
  frontend/src/main/components/Jobs/UpdateCoursesJobForm.js
Labels: f22-6pm-1

#51 YL - Course Over Time Backend Part One and Part Two
  src/main/java/edu/ucsb/cs156/courses/collections/ConvertedSectionCollection.java
  src/main/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeControllerTests.java
Labels: f22-6pm-1

#46 Ethan - Update Courses for all Subjects BACKEND
  .DS_Store
  src/main/java/edu/ucsb/cs156/courses/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataOneQuarterJob.java
  src/main/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataOneQuarterJobFactory.java
  src/test/java/edu/ucsb/cs156/courses/controllers/JobsControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataOneQuarterJobFactoryTests.java
  src/test/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataOneQuarterJobTests.java
Labels: f22-6pm-1, Merge Candidate: Needs QA deploy
